// Generates app/tokens.css (and tokens/resolved.json for check.mjs) from tokens/tokens.json.
// OKLCH values are converted to sRGB hex the way CSS Color 4 specifies: OKLab -> LMS -> linear RGB -> gamma,
// with out-of-gamut colours mapped by reducing chroma until they fit (not by clipping channels).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));

const OKLCH = /^oklch\(\s*([\d.]+)%\s+([\d.]+)\s+([\d.]+)\s*\)$/;

function oklchToLinearSrgb(L, C, hDeg) {
  const h = (hDeg * Math.PI) / 180;
  const a = C * Math.cos(h), b = C * Math.sin(h);
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3, m = m_ ** 3, s = s_ ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}
const inGamut = (rgb) => rgb.every((c) => c >= -0.0005 && c <= 1.0005);
const gamma = (c) => {
  c = Math.min(1, Math.max(0, c));
  return c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055;
};
const hex = (rgb) => "#" + rgb.map((c) => Math.round(gamma(c) * 255).toString(16).padStart(2, "0")).join("");

/** sRGB hex for an OKLCH colour; chroma is reduced by binary search when the colour falls outside sRGB. */
export function oklchToHex(value) {
  const m = OKLCH.exec(value);
  if (!m) throw new Error(`Not an OKLCH colour: ${value}`);
  const L = Number(m[1]) / 100;
  let C = Number(m[2]);
  const H = Number(m[3]);
  let rgb = oklchToLinearSrgb(L, C, H);
  if (!inGamut(rgb)) {
    let lo = 0, hi = C;
    for (let i = 0; i < 24; i++) {
      const mid = (lo + hi) / 2;
      if (inGamut(oklchToLinearSrgb(L, mid, H))) lo = mid;
      else hi = mid;
    }
    C = lo;
    rgb = oklchToLinearSrgb(L, C, H);
  }
  return hex(rgb);
}

const resolveColor = (value) => (value.startsWith("oklch(") ? oklchToHex(value) : value.toLowerCase());

// Palette: every step resolved to hex.
const palette = {};
for (const [ramp, steps] of Object.entries(tokens.palette)) {
  for (const [step, value] of Object.entries(steps)) palette[`${ramp}.${step}`] = resolveColor(value);
}
// Semantic: references into the palette only (the PrismSystem rule: semantic -> palette, never foundation).
const semantic = {};
for (const [name, ref] of Object.entries(tokens.semantic)) {
  const m = /^\{([a-z]+)\.(\d+)\}$/.exec(ref);
  if (!m || !(`${m[1]}.${m[2]}` in palette)) throw new Error(`Semantic token "${name}" must reference a palette step; got ${ref}`);
  semantic[name] = { ref: `${m[1]}-${m[2]}`, hex: palette[`${m[1]}.${m[2]}`] };
}

const lines = [
  "/* GENERATED by tokens/build.mjs from tokens/tokens.json. Do not edit by hand: run `npm run tokens`. */",
  ":root {",
  "  /* Palette (foundation colours, sRGB hex resolved from OKLCH). The UI never references these directly. */",
  ...Object.entries(palette).map(([k, v]) => `  --md-${k.replace(".", "-")}: ${v};`),
  "  /* Semantic colours: what components consume. */",
  ...Object.entries(semantic).map(([k, v]) => `  --md-${k}: var(--md-${v.ref}); /* ${v.hex} */`),
  `  --md-scrim: ${tokens.scrim};`,
  ...Object.entries(tokens.alpha).filter(([k]) => !k.startsWith("$")).map(([k, v]) => `  --md-${k}: ${v};`),
  "  /* Elevation (ink-tinted shadows). */",
  ...Object.entries(tokens.elevation).map(([k, v]) => `  --md-elevation-${k}: ${v};`),
  "  /* Space, radius, layers. */",
  ...Object.entries(tokens.space).map(([k, v]) => `  --md-space-${k}: ${v};`),
  ...Object.entries(tokens.radius).map(([k, v]) => `  --md-radius-${k}: ${v};`),
  ...Object.entries(tokens.z).map(([k, v]) => `  --md-z-${k}: ${v};`),
  "  /* Type. */",
  ...Object.entries(tokens.type).map(([k, v]) => `  --md-${k}: ${v};`),
  "  /* Motion (curves and durations from emilkowalski/skills; see PLANO-UI-MOTION.md 7.1). */",
  ...Object.entries(tokens.motion).map(([k, v]) => `  --${k}: ${v};`),
  "}",
  "",
];
writeFileSync(join(here, "..", "app", "tokens.css"), lines.join("\n"));
writeFileSync(
  join(here, "resolved.json"),
  JSON.stringify({ palette, semantic: Object.fromEntries(Object.entries(semantic).map(([k, v]) => [k, v.hex])), pairs: tokens.pairs }, null, 2),
);
console.log(`tokens.css: ${Object.keys(palette).length} palette + ${Object.keys(semantic).length} semantic tokens`);
